### PR TITLE
Update crystal version to 1.0

### PR DESCRIPTION
**Pull request by Leeingnyo**
Update crystal version and `shard.yml`

### CODE REVIEW

**Comment by hkalexling** [comment]
Thanks for the PR! I think the workflow is failing because the `mangadex` shard has to be upgraded first. It's maintained by me and I will work on it soon.

**Comment by hkalexling** [comment]
Since we will be moving the built-in MangaDex integration to a plugin (WIP in branch `feature/plugin-v2`), the `mangadex` shard is no longer needed. I will remove the dependency from `dev` and then merge this.

**Comment by Leeingnyo** [comment]
By the way, I forgot to edit Dockerfiles for arm architectures..

**Comment by hkalexling** [comment]
Thanks for the reminder. Don't worry I will update and test the ARM Dockerfiles myself.

**Comment by hkalexling** [comment]
I fixed the workflow and updated the ARM Dockerfiles, but I haven't tested them yet. I will test them on my ARM devices over the weekend and if everything goes well I will then merge this PR :)

**Review by hkalexling — APPROVED** [review]

**Comment by hkalexling** [comment]
@Leeingnyo Thanks for the PR! It's working fine on ARM. I also fixed the "Executing query" problem you mentioned on Gitter. It was logged by `crystal-db` from https://github.com/crystal-lang/crystal-db/blob/bf5ca75d1ace7e15b00ca03ad21728b8b00cf007/src/db/statement.cr#L145

**Pull request merged**
